# -*- coding: utf-8 -*-
"""student_sales_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14CW0I_6Tf5n2G1QfcDm2c12dMmC-xVc4
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Sales Dashboard", layout="wide")

st.title("📊 Sales Dashboard")

# File upload
uploaded_file = st.file_uploader("Upload your Excel file", type=["xlsx"])

if uploaded_file is not None:
    try:
        df = pd.read_excel(uploaded_file)

        # Clean column names
        df.columns = df.columns.astype(str)
        df.columns = df.columns.str.strip()

        # Convert 'Order Date' to datetime if it exists
        if 'Order Date' in df.columns:
            df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')
            df.dropna(subset=['Order Date'], inplace=True)

        st.subheader("📄 Data Preview")
        st.dataframe(df)

        # Display summary statistics
        st.subheader("🔢 Descriptive Statistics")
        st.dataframe(df.describe())

        # --- Sidebar Filters ---
        st.sidebar.header("Filter Data")

        # Category filter
        if 'Category' in df.columns:
            categories = ['All'] + list(df['Category'].unique())
            selected_category = st.sidebar.selectbox("Select Category", categories)
        else:
            selected_category = 'All'

        # Region filter
        if 'Region' in df.columns:
            regions = ['All'] + list(df['Region'].unique())
            selected_region = st.sidebar.selectbox("Select Region", regions)
        else:
            selected_region = 'All'

        # Date Range filter
        if 'Order Date' in df.columns:
            min_date = df['Order Date'].min().to_pydatetime()
            max_date = df['Order Date'].max().to_pydatetime()
            date_range = st.sidebar.slider(
                "Select Date Range",
                min_value=min_date,
                max_value=max_date,
                value=(min_date, max_date),
                format="YYYY-MM-DD"
            )
            start_date, end_date = date_range
        else:
            start_date, end_date = None, None

        # Apply filters
        filtered_df = df.copy()
        if selected_category != 'All':
            filtered_df = filtered_df[filtered_df['Category'] == selected_category]
        if selected_region != 'All':
            filtered_df = filtered_df[filtered_df['Region'] == selected_region]
        if start_date and end_date:
            filtered_df = filtered_df[(filtered_df['Order Date'] >= start_date) & (filtered_df['Order Date'] <= end_date)]

        # --- Download Filtered Data ---
        st.subheader("📥 Download Data")
        csv_data = filtered_df.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="Download Filtered Data as CSV",
            data=csv_data,
            file_name='filtered_sales_data.csv',
            mime='text/csv',
        )

        # --- Basic Metrics ---
        st.subheader("📈 Key Metrics")
        col1, col2 = st.columns(2)

        if 'Sales' in filtered_df.columns:
            total_sales = filtered_df['Sales'].sum()
            col1.metric("Total Sales", f"${total_sales:,.2f}")

        if 'Profit' in filtered_df.columns:
            total_profit = filtered_df['Profit'].sum()
            col2.metric("Total Profit", f"${total_profit:,.2f}")

        # --- Charts ---
        st.subheader("📊 Visualizations")

        # Sales by Category
        if 'Category' in filtered_df.columns and 'Sales' in filtered_df.columns:
            category_sales = filtered_df.groupby('Category')['Sales'].sum().reset_index()
            fig1 = px.bar(category_sales, x='Category', y='Sales', color='Category', title=f"Sales by Category ({selected_category} / {selected_region})")
            st.plotly_chart(fig1, use_container_width=True)

        # Sales over time
        if 'Order Date' in filtered_df.columns and 'Sales' in filtered_df.columns:
            # Make sure 'Order Date' is datetime before grouping
            filtered_df['Order Date'] = pd.to_datetime(filtered_df['Order Date'], errors='coerce')
            time_series_df = filtered_df.groupby(pd.Grouper(key='Order Date', freq='M'))['Sales'].sum().reset_index()
            fig2 = px.line(time_series_df, x='Order Date', y='Sales', title=f"Sales Over Time ({selected_category} / {selected_region})")
            st.plotly_chart(fig2, use_container_width=True)

        # Region wise
        if 'Region' in filtered_df.columns and 'Sales' in filtered_df.columns:
            region_sales = filtered_df.groupby('Region')['Sales'].sum().reset_index()
            fig3 = px.pie(region_sales, names='Region', values='Sales', title=f"Sales by Region ({selected_category} / {selected_region})")
            st.plotly_chart(fig3, use_container_width=True)

        # Sales vs Profit Scatter Plot
        if 'Sales' in filtered_df.columns and 'Profit' in filtered_df.columns:
            fig_scatter = px.scatter(filtered_df, x='Sales', y='Profit',
                                     title=f"Sales vs Profit ({selected_category} / {selected_region})")
            st.plotly_chart(fig_scatter, use_container_width=True)

        # Sales Distribution by Category Box Plot
        if 'Category' in filtered_df.columns and 'Sales' in filtered_df.columns:
            fig_box = px.box(filtered_df, x='Category', y='Sales',
                             title=f"Sales Distribution by Category ({selected_category} / {selected_region})")
            st.plotly_chart(fig_box, use_container_width=True)


    except Exception as e:
        st.error(f"Error: {e}")

else:
    st.info("👆 Please upload your Excel file to get started!")

import plotly.express as px

# Assuming average_profit_per_region DataFrame is already available
# from previous steps (cell b7b64048 or 1a3298ae)

fig_avg_profit_region = px.bar(average_profit_per_region,
                               x='Region',
                               y='Profit',
                               color='Region',
                               title='Average Profit per Region (Sample Data)')

fig_avg_profit_region.show()

import plotly.express as px

# Group df_sample by Order Date and sum Sales
time_series_sample = df_sample.groupby('Order Date')['Sales'].sum().reset_index()

# Create a line plot using Plotly Express
fig_line_sample = px.line(time_series_sample, x='Order Date', y='Sales', title='Total Sales Over Time (Sample Data)')

# Display the chart
fig_line_sample.show()

average_profit_per_region = df_sample.groupby('Region')['Profit'].mean().reset_index()
print("Average Profit per Region:")
print(average_profit_per_region)

category_total_sales = df_sample.groupby('Category')['Sales'].sum().reset_index()
top_category = category_total_sales.loc[category_total_sales['Sales'].idxmax()]

print("Top-performing category by total sales:")
print(top_category)

print("Unique values in 'Product' column:")
print(df['Product'].unique())

import plotly.express as px

# Group df by 'Product' and sum 'Revenue'
product_revenue = df.groupby('Product')['Revenue'].sum().reset_index()

# Create a bar chart using Plotly Express
fig_product_revenue = px.bar(product_revenue, x='Product', y='Revenue', color='Product', title='Total Revenue by Product Category')

# Display the chart
fig_product_revenue.show()

import pandas as pd

# Load the Excel file into a DataFrame without assuming a header initially
excel_file_path = '/content/batch 8 dataset-sales data.xlsx'
df = pd.read_excel(excel_file_path, header=None)

# Promote the second row of the data (index 1) to be the column headers
df.columns = df.iloc[1]
df = df[2:].copy()

# Ensure column names are clean (important after promoting headers)
df.columns = df.columns.astype(str).str.strip()

# Convert 'Price' and 'Quantity' columns to numeric, coercing errors to NaN
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

# Drop rows where 'Price' or 'Quantity' became NaN after conversion, as they are essential for revenue calculation
df.dropna(subset=['Price', 'Quantity'], inplace=True)

# Calculate the 'Revenue' column
df['Revenue'] = df['Price'] * df['Quantity']

# Calculate the total revenue
total_revenue = df['Revenue'].sum()

print(f"Total Revenue: ${total_revenue:,.2f}")

import pandas as pd

# Load the Excel file into a DataFrame without assuming a header initially
excel_file_path = '/content/batch 8 dataset-sales data.xlsx'
df = pd.read_excel(excel_file_path, header=None)

# Promote the second row of the data (index 1) to be the column headers
df.columns = df.iloc[1]
df = df[2:].copy()

# Ensure column names are clean (important after promoting headers)
df.columns = df.columns.astype(str).str.strip()

display(df.head())

import plotly.express as px

fig_box_sample = px.box(df_sample, x='Category', y='Sales', title='Sales Distribution by Category (Sample Data)')
fig_box_sample.show()

display(df_sample.describe())

average_profit_per_region = df_sample.groupby('Region')['Profit'].mean().reset_index()
print("Average Profit per Region:")
print(average_profit_per_region)

correlation = df_sample['Sales'].corr(df_sample['Profit'])
print(f"Correlation between Sales and Profit: {correlation:.4f}")

import plotly.express as px

fig_revenue_profit_df = px.scatter(df, x='Revenue', y='Profit',
                                     title='Revenue vs Profit for Main Dataset')
fig_revenue_profit_df.show()

import plotly.express as px

fig_scatter_sample = px.scatter(df_sample, x='Sales', y='Profit', title='Sample Sales vs Profit')
fig_scatter_sample.show()

import plotly.express as px

# Group df_sample by Category and sum Sales
category_sales_sample = df_sample.groupby('Category')['Sales'].sum().reset_index()

# Create a bar chart using Plotly Express
fig_sample = px.bar(category_sales_sample, x='Category', y='Sales', color='Category', title='Sample Sales by Category')

# Display the chart
fig_sample.show()

import pandas as pd
from datetime import datetime, timedelta

# Generate sample data
data = {
    'Order Date': [datetime.now() - timedelta(days=x) for x in range(20)],
    'Category': ['Electronics', 'Clothing', 'Home', 'Electronics', 'Clothing', 'Home', 'Electronics', 'Clothing', 'Home', 'Electronics',
                   'Electronics', 'Clothing', 'Home', 'Electronics', 'Clothing', 'Home', 'Electronics', 'Clothing', 'Home', 'Electronics'],
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
                 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': [150.00, 200.50, 75.25, 300.00, 120.00, 80.00, 250.00, 180.00, 90.00, 320.00,
              160.00, 210.50, 85.25, 310.00, 130.00, 90.00, 260.00, 190.00, 100.00, 330.00],
    'Profit': [30.00, 50.10, 15.00, 60.00, 25.00, 10.00, 45.00, 35.00, 20.00, 70.00,
               32.00, 52.10, 17.00, 62.00, 27.00, 12.00, 47.00, 37.00, 22.00, 72.00]
}

df_sample = pd.DataFrame(data)

# Save to Excel
excel_file_path = 'sample_sales_data.xlsx'
df_sample.to_excel(excel_file_path, index=False)

print(f"Sample Excel file '{excel_file_path}' generated successfully.")
print("You can download this file from the file browser on the left, then upload it to your Streamlit dashboard.")